#!/usr/bin/env node
// Reproducible UI-only subset, not a general-purpose Chinese input font.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const [font, converter] = process.argv.slice(2);
if (!font || !converter) throw new Error('Usage: node tools/generate_ui_fonts.mjs <SourceHanSansSC-Normal.otf> <lv_font_conv.js>');
const sha = createHash('sha256').update(readFileSync(font)).digest('hex');
if (sha !== '7e5b7e586262f5e187c3397935b3a0dfbe28e08a916be0f60ec7fee2b50abd6d') throw new Error('Font checksum mismatch');
const files = readdirSync(resolve(root, 'main')).filter(f => /^(demo_.*|main|pet_ui_text)\.c$/.test(f)).sort();
const symbols = new Set();
for (const file of files) {
    const source = readFileSync(resolve(root, 'main', file), 'utf8');
    // Include non-ASCII literals, not comments. There are no concatenated
    // multi-line or escaped non-ASCII glyphs in the current UI copy.
    for (const match of source.matchAll(/"(?:[^"\\]|\\.)*"/g)) {
        for (const char of match[0]) if (char.codePointAt(0) > 127) symbols.add(char);
    }
}
const chars = [...symbols].sort((a, b) => a.codePointAt(0) - b.codePointAt(0)).join('');
for (const size of [14, 20]) {
    const result = spawnSync(process.execPath, [resolve(converter),
        '--font', resolve(font), '--size', String(size), '--bpp', '4',
        '--range', '0x20-0x7e', '--symbols', chars, '--no-compress', '--no-kerning',
        '--format', 'lvgl', '--lv-include', 'lvgl.h',
        '--lv-font-name', 'passport_zh_' + size,
        '-o', resolve(root, 'assets/fonts/passport_zh_' + size + '.c')],
        { stdio: 'inherit' });
    if (result.status !== 0) process.exit(result.status || 1);
    const output = resolve(root, 'assets/fonts/passport_zh_' + size + '.c');
    const generated = readFileSync(output, 'utf8').replace(/ \* Opts:.*\n/, ' * Generated by tools/generate_ui_fonts.mjs; see LICENSE.txt (SIL OFL 1.1).\n');
    writeFileSync(output, generated.trimEnd() + '\n');
}
console.log('Generated Passport UI subset: ASCII + ' + symbols.size + ' non-ASCII glyphs, 14/20 px');
